[project]
name = "polars-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.1.0",
    "polars>=1.27.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
